/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_utopa_arserver_location_jni_LocationSDK */

#ifndef _Included_com_utopa_arserver_location_jni_LocationSDK
#define _Included_com_utopa_arserver_location_jni_LocationSDK
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_utopa_arserver_location_jni_LocationSDK
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_utopa_arserver_localization_jni_LocalizationSDK_init
  (JNIEnv *, jclass, jstring, jstring, jstring,jint key);

/*
 * Class:     com_utopa_arserver_location_jni_LocationSDK
 * Method:    destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_utopa_arserver_localization_jni_LocalizationSDK_destroy
  (JNIEnv *, jclass,jint key);

/*
 * Class:     Java_com_utopa_arserver_localization_jni_LocalizationSDK_
 * Method:    trackMonocular
 * Signature: ([BID)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_utopa_arserver_localization_jni_LocalizationSDK_trackMonocular
  (JNIEnv * env, jclass,jbyteArray inputImage, jint bufferLength, jdouble focus_length, jint devType, 
                jfloatArray poseArray, jint bUseInitGuessJint, jint key);

#ifdef __cplusplus
}
#endif
#endif
