/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_utopa_arserver_localizationmgt_jni_MakeMapSDK */

#ifndef _Included_com_utopa_arserver_makemap_jni_MakeMapSDK
#define _Included_com_utopa_arserver_makemap_jni_MakeMapSDK
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_utopa_arserver_makemap_jni_MakeMapSDK_initSDK(JNIEnv * env, jobject, jstring voc_path1, jstring voc_path2, jstring voc_path3 );
/*
 * Class:     com_utopa_arserver_localizationmgt_jni_MakeMapSDK
 * Method:    buildMap
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_utopa_arserver_makemap_jni_MakeMapSDK_buildMap
  (JNIEnv * env, jobject, jstring work_space, jstring resource_path, jboolean build_dense,jint quality, jstring key, jobject buildMapCallback);

/*
 * Class:     com_utopa_arserver_localizationmgt_jni_MakeMapSDK
 * Method:    getTaskState
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_utopa_arserver_makemap_jni_MakeMapSDK_getTaskState
  (JNIEnv *);


JNIEXPORT jint JNICALL Java_com_utopa_arserver_makemap_jni_MakeMapSDK_setProgressCallBack
  (JNIEnv * env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
